name: Flutter — Test & Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Analyze → Test (fast)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'   # pin to stable for reproducibility
          channel: 'stable'
          architecture: x64

      - name: Install deps
        run: flutter pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Static analysis
        run: flutter analyze

      - name: Run tests (with coverage)
        run: flutter test --coverage
